@connector_daemon_HostAddress = http://localhost:5739

### Health
GET {{connector_daemon_HostAddress}}/health
Accept: application/json

### Job event webhook
POST {{connector_daemon_HostAddress}}/api/v1/job-events
Content-Type: application/json
Accept: application/json

{
  "job": "some-job",
  "build": 7,
  "commit": "4d7c3a6c8e8a9d3b3f6b8d2b5e4a1c7d9e0f1234",
  "branch": "master",
  "status": "success",
  "gitUrl": "https://dev.azure.com/some-org/some-project/_git/some-repository",
  "buildUrl": "https://jenkins.example.com/job/connector-daemon/job/main/123/"
}

### List monitored repositories
GET {{connector_daemon_HostAddress}}/api/system/jobs/repositories
Accept: application/json

### List repository jobs
GET {{connector_daemon_HostAddress}}/api/system/jobs/some-repo
Accept: application/json
